### ISSUE TITLE
Login requerido

### ISSUE THREAD

**Issue by ifernandezm** [multidadosti-erp/odoo-rest#1]
Hola,
estoy intentado usar el conector con una instancia de odoo en la misma máquina.
Tenemos el resource de users, pero al intentar acceder a él solicita usuario y contraseña.
Mi pregunta es ¿qué usuario hay que introducir? 
He probado con el usuario de la base de datos, con el de odoo, admin admin, y no hay forma

Gracias

**Comment by mstuttgart** [comment]
Its depends of access level required. I create a user with read and write permission to modules of my database.
